//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietOCR.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietOCR.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Help.
        /// </summary>
        internal static string _Help {
            get {
                return ResourceManager.GetString("_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string _of_ {
            get {
                return ResourceManager.GetString("_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About .
        /// </summary>
        internal static string About_ {
            get {
                return ResourceManager.GetString("About_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Process Status.
        /// </summary>
        internal static string BatchProcessStatus {
            get {
                return ResourceManager.GetString("BatchProcessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load image..
        /// </summary>
        internal static string Cannotloadimage {
            get {
                return ResourceManager.GetString("Cannotloadimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process .
        /// </summary>
        internal static string Cannotprocess {
            get {
                return ResourceManager.GetString("Cannotprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check output file(s) in .
        /// </summary>
        internal static string check_output_in {
            get {
                return ResourceManager.GetString("check_output_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been created..
        /// </summary>
        internal static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input incomplete..
        /// </summary>
        internal static string Inputincomplete {
            get {
                return ResourceManager.GetString("Inputincomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input invalid..
        /// </summary>
        internal static string Inputinvalid {
            get {
                return ResourceManager.GetString("Inputinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        internal static string Load_image {
            get {
                return ResourceManager.GetString("Load_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load an image..
        /// </summary>
        internal static string LoadImage {
            get {
                return ResourceManager.GetString("LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading completed..
        /// </summary>
        internal static string Loading_completed {
            get {
                return ResourceManager.GetString("Loading_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image....
        /// </summary>
        internal static string Loading_image {
            get {
                return ResourceManager.GetString("Loading_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge TIFF running....
        /// </summary>
        internal static string Merge_running {
            get {
                return ResourceManager.GetString("Merge_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge TIFF completed. .
        /// </summary>
        internal static string Mergecompleted {
            get {
                return ResourceManager.GetString("Mergecompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR completed..
        /// </summary>
        internal static string OCRcompleted {
            get {
                return ResourceManager.GetString("OCRcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Operation.
        /// </summary>
        internal static string OCROperation {
            get {
                return ResourceManager.GetString("OCROperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR running....
        /// </summary>
        internal static string OCRrunning {
            get {
                return ResourceManager.GetString("OCRrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image File.
        /// </summary>
        internal static string OpenImageFile {
            get {
                return ResourceManager.GetString("OpenImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string Page_ {
            get {
                return ResourceManager.GetString("Page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readme_cs.html.
        /// </summary>
        internal static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string Save_As {
            get {
                return ResourceManager.GetString("Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan completed..
        /// </summary>
        internal static string Scancompleted {
            get {
                return ResourceManager.GetString("Scancompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Operation.
        /// </summary>
        internal static string ScanningOperation {
            get {
                return ResourceManager.GetString("ScanningOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language..
        /// </summary>
        internal static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split PDF completed..
        /// </summary>
        internal static string SplitPDF_completed {
            get {
                return ResourceManager.GetString("SplitPDF_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split PDF running....
        /// </summary>
        internal static string SplitPDF_running {
            get {
                return ResourceManager.GetString("SplitPDF_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to split the PDF file into smaller files before proceed..
        /// </summary>
        internal static string suggest_split {
            get {
                return ResourceManager.GetString("suggest_split", resourceCulture);
            }
        }
    }
}
